default_install_hook_types: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: check_commiter_user_name
        name: Check committer user name
        entry: python check_user_name.py
        language: python
        stages: [pre-commit]
